[package]
name = "cor-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote2 = "0.9"
proc-macro2 = { version = "1", features = ["span-locations"] }
syn = { version = "2", features = ["extra-traits"] }
